### ISSUE TITLE
BUG: error compiling with Maven

### ISSUE THREAD

**Issue by fante76** [pontusbostrom/InlineDateRangeField#1] opened 2017-08-31 10:12 UTC
Vaadin 8.1.1
Java 1.8
Eclipse Oxygen

I've just added this add-on to maven dependency on my project. When I re-compile widgetset this error happens:

`[INFO] Compiling module AppWidgetset`
`[INFO]    Tracing compile failure path for type 'org.vaadin.support.pontus.daterangefield.client.VDateRangeFieldCalendar'`
`[INFO]       [ERROR] Errors in 'jar:file:/C:/Users/luca.pertile/.m2/repository/org/vaadin/support/pontus/daterangefield/0.1/daterangefield-0.1.jar!/org/vaadin/support/pontus/daterangefield/client/VDateRangeFieldCalendar.java'`
`[INFO]          [ERROR] Line 14: The type VDateRangeFieldCalendar must implement the inherited abstract method VDateField<DateResolution>.supportsTime()`
`[INFO]    [ERROR] Aborting compile due to errors in some input files`

**Comment by pontusbostrom** [comment] 2018-03-22 14:21
This is due to an api change in the Vaadin 8 series. The problem is fixed in commit https://github.com/pontusbostrom/InlineDateRangeField/commit/53f81346dde5ee1b3efe9953c5fe8d11cc3c3505

**Closed as completed by pontusbostrom** 2018-03-22 14:21 UTC
